### ISSUE TITLE
CPS 5.2.4: Add clarifying text regarding the code approval/merging methodology on the boulder repo

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/cp-cps#76] opened 2021-06-21 21:05 UTC
> 5.2.4 Roles requiring separation of duties
> 
> Nobody with the ability to deploy software to ISRG PKI systems (e.g. Systems Administrators) may have the ability to commit code to core CA software. The reverse is also true.

**Comment by pgporada** [comment] 2021-06-21 21:46
CPS 6.6.1 is related https://letsencrypt.org/documents/isrg-cps-v3.3/#6.6.1-system-development-controls

> When ISRG develops software to be used in CA operations, software development policies are put into place and methodologies are followed in order to ensure software quality and integrity. This always includes a requirement for peer review of code changes. Unit testing is strongly encouraged. Code commit privileges are granted only to qualified and trusted contributors. Nobody with the ability to deploy software to ISRG PKI systems (e.g. Systems Administrators) may have the ability to commit code to core CA software. The reverse is also true.

**Comment by aarongable** [comment] 2021-07-14 18:11
Duplicate of #87

**Closed by aarongable** 2021-07-14 18:11 UTC
